In [7]:

%run solutionMarc.py

0
[[4.51468806]]eh bah ca c'est x mon gars
[[1.79740812]]eh bah ca c'est f
[[4.51468806]]eh ca c'est v 
1
[[4.51468806]
 [2.57529935]]eh bah ca c'est x mon gars
[[ 1.79740812]
 [-0.07529935]]eh bah ca c'est f
[[4.51468806]
 [2.57529935]]eh ca c'est v 
2
[[4.51468806]
 [2.57529935]
 [4.51491346]]eh bah ca c'est x mon gars
[[ 1.79740812]
 [-0.07529935]
 [-2.01491346]]eh bah ca c'est f
[[4.51468806]
 [2.57529935]
 [4.51491346]]eh ca c'est v 
3
[[4.51468806]
 [2.57529935]
 [4.51491346]
 [0.        ]]eh bah ca c'est x mon gars
[[ 1.79740812]
 [-0.07529935]
 [-2.01491346]
 [-2.5       ]]eh bah ca c'est f
[[4.51468806]
 [2.57529935]
 [4.51491346]
 [0.        ]]eh ca c'est v 
4
[[4.51468806]
 [2.57529935]
 [4.51491346]
 [0.        ]
 [1.39148904]]eh bah ca c'est x mon gars
[[ 1.79740812]
 [-0.07529935]
 [-2.01491346]
 [-2.5       ]
 [-1.10851096]]eh bah ca c'est f
[[4.51468806]
 [2.57529935]
 [4.51491346]
 [0.        ]
 [1.39148904]]eh ca c'est v 
5
[[4.51468806]
 [2.57529935]
 [4.51491346]
 [

18
[[4.51468806]
 [2.57529935]
 [4.51491346]
 [0.        ]
 [1.39148904]
 [3.76931831]
 [5.        ]
 [4.33910664]
 [2.02963383]
 [3.1083556 ]
 [0.76688853]
 [4.6240551 ]
 [2.31595028]
 [1.74001443]
 [3.40004073]
 [2.8146324 ]
 [0.4068491 ]
 [1.12613038]
 [2.44381032]]eh bah ca c'est x mon gars
[[ 1.79740812]
 [-0.07529935]
 [-2.01491346]
 [-2.5       ]
 [-1.10851096]
 [-1.26931831]
 [-2.5       ]
 [-1.83910664]
 [-0.47036617]
 [-0.6083556 ]
 [-1.73311147]
 [-2.1240551 ]
 [-0.18404972]
 [-0.75998557]
 [-0.90004073]
 [-0.3146324 ]
 [-2.0931509 ]
 [-1.37386962]
 [-0.05618968]]eh bah ca c'est f
[[4.51468806]
 [2.57529935]
 [4.51491346]
 [0.        ]
 [1.39148904]
 [3.76931831]
 [5.        ]
 [4.33910664]
 [2.02963383]
 [3.1083556 ]
 [0.76688853]
 [4.6240551 ]
 [2.31595028]
 [1.74001443]
 [3.40004073]
 [2.8146324 ]
 [0.4068491 ]
 [1.12613038]
 [2.44381032]]eh ca c'est v 
19
[[4.51468806]
 [2.57529935]
 [4.51491346]
 [0.        ]
 [1.39148904]
 [3.76931831]
 [5.        ]
 [4.33910664]
 [2.0

In [188]:
domain = np.array([[0, 5]])

In [84]:
print(domain[:, 0] + (domain[:, 1] - domain[:, 0]) * \
                 np.random.rand(domain.shape[0]))

[2.38935708]


In [59]:
result = [54, 1.2]
print(np.clip(result[0], *domain[0]))

5


In [62]:
x_values = []
x_values.append(np.clip(result[0], *domain[0]))
x_values[0]

5

In [198]:
np.random.rand(

array([0.26515039])